config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get 'sign_out', :to => 'devise/sessions#destroy'
  end
  resources :needees
  resources :users, only: [:edit, :update]

  authenticated :user do
    root to: 'needees#index', as: :authenticated_root
  end
  root to: 'home#land'

end

app/models/locality.rb
# == Schema Information
#
# Table name: localities
#
#  id         :integer          not null, primary key
#  name       :string
#  latitude   :string
#  longitude  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Locality < ActiveRecord::Base
end

app/models/needee.rb
# == Schema Information
#
# Table name: needees
#
#  id           :integer          not null, primary key
#  name         :string
#  phone        :string
#  locality_id  :integer
#  address      :text
#  details      :text
#  type_of_help :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Needee < ActiveRecord::Base
  module HelpType
    GET_OUT   = {code: 1, text: "Getting Out of Chennai"}
    FOOD      = {code: 2, text: "Food, Clothes and Supplies"}
    SHELTER   = {code: 3, text: "Shelter"}
    SEARCH    = {code: 4, text: "Search and Find and Rescue"}
    VOLUNTEER = {code: 5, text: "Volunteer Work"}
    TRANSPORT = {code: 6, text: "Transport"}

    def self.needs
      [GET_OUT, FOOD, SHELTER, SEARCH, TRANSPORT].collect{|need| OpenStruct.new need}
    end

    def self.all_needs
      [GET_OUT, FOOD, SHELTER, SEARCH, TRANSPORT, VOLUNTEER].collect{|need| OpenStruct.new need}
    end

    def self.helps
      [GET_OUT, FOOD, SHELTER, SEARCH, TRANSPORT, VOLUNTEER].collect{|help| [help[:text], help[:code]]}
    end

    def self.help_name(code)
      self.helps.each do |arr|
        return arr[0] if arr[1] == code
      end
    end
  end

  belongs_to :locality
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  email              :string
#  encrypted_password :string
#  sign_in_count      :integer          default(0), not null
#  current_sign_in_at :datetime
#  last_sign_in_at    :datetime
#  current_sign_in_ip :string
#  last_sign_in_ip    :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  provider           :string
#  uid                :string
#  name               :string
#  image              :string
#  phone              :string
#  locality_id        :integer
#  type_of_help       :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :database_authenticatable, :lockable, :recoverable, :rememberable, :timeoutable, :validatable and :omniauthable
  devise :registerable, :trackable, :omniauthable, :omniauth_providers => [:facebook]

  belongs_to :locality

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      # user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def profile_incomplete?
    [self.locality, self.type_of_help, self.phone].select(&:blank?).length > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new_session_path(scope)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def land
  end
end

app/controllers/needees_controller.rb
class NeedeesController < ApplicationController
  def index
    if current_user.profile_incomplete?
      redirect_to edit_user_path(current_user)
      return
    end
    if params[:help_type]
      @help_type = params[:help_type].to_i
      @locality_id = params[:locality_id].to_i
    else
      @help_type = current_user.type_of_help
      @locality_id = current_user.locality_id
    end

    if @help_type == Needee::HelpType::VOLUNTEER[:code]
      @needees = Needee.where(locality_id: @locality_id).order(id: :desc)
    else
      @needees = Needee.where(type_of_help: @help_type, locality_id: @locality_id).order(id: :desc)
    end
    @volunteers = User.where(type_of_help: Needee::HelpType::VOLUNTEER[:code], locality_id: @locality_id).order(id: :desc)
    @localities = Locality.all
  end

  def new
    @needee = Needee.new
    @localities = Locality.all
  end

  def create
    @needee = Needee.new(needee_params)
    if verify_recaptcha(model: @needee) && @needee.save
      flash[:notice] = "A volunteer will contact you soon"
      redirect_to root_path
    else
      @localities = Locality.all
      flash[:alert] = "Please enter all details"
      render :new
    end
  end

private
  def needee_params
    params.require(:needee).permit(:name, :phone, :alt_phone, :locality_id, :type_of_help, :address, :details)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @localities = Locality.all
  end

  def update
    current_user.update_attributes(user_params)
    if current_user.profile_incomplete?
      flash[:alert] = "Please fill all the details"
      redirect_to edit_user_path(current_user)
    else
      redirect_to root_path
    end
  end

private
  def user_params
    params.require(:user).permit(:locality_id, :type_of_help, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_tag(msg, msg_type)
    return unless msg.present?
    if msg_type == "notice"
      msg_type = "info"
    elsif msg_type == "alert"
      msg_type = "danger"
    end

    content_tag(:div, class: "alert alert-#{msg_type} alert-dismissible", role: "alert") do
      button_tag(class: "close", "data-dismiss" => "alert") do
        content_tag(:span, raw("&times;"), "aria-hidden" => true) +
          content_tag(:span, "Close", class: "sr-only")
      end + msg
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/needees_helper.rb
module NeedeesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_footer.html.erb
<footer class="navbar-fixed-bottom">
  <div class="container">
    <p>By signing up, you agree that you respect the privacy of people and do not use the contact details for anything other than the rescue mission being carried out.</p>
    <p>Your data is safe. We won't use it for anything other than this rescue mission</p>
    <p>
      Built with compassion by
      <a href="http://www.codeastra.com">Code Astra</a> team.
    </p>
  </div>
</footer>

app/views/common/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Connect Chennai", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to raw(image_tag(current_user.image, class: "img-circle") + "Logout"), sign_out_path, method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/home/land.html.erb
<div class="jumbotron text-center">
  <h1>Connect Chennai</h1>
  <p>Connecting Volunteers and the needy.</p>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <div class="well">
          <%= link_to "I Need Help", new_needee_path, class: "btn btn-block btn-primary btn-lg" %>
          <ul class="text-left well">
            <li>Post information about your needs</li>
            <li>Post information about your nears and dears who need help</li>
          </ul>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <%= link_to "I Can Help (Facebook Login)", user_omniauth_authorize_path(:facebook), class: "btn btn-block btn-primary btn-lg" %>
          <ul class="text-left well">
            <li>Search for people looking for help in your locality</li>
            <li>Find fellow volunteers who would be willing to join you</li>
          </ul>
          <small>(We won't post on your wall)</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<% website_title = "Connect Chennai - Bridging those who need with those who can" %>
<% website_description = "Seek and get help for yourself or your relatives and friends in Chennai. Volunteers can connect with fellow volunteers and people looking for help in their locality" %>
<!DOCTYPE html>
<html>
<head>
  <title><%= website_title %></title>
  <meta property="og:site_name" content="<%= website_title %>"/>
  <meta property="og:title" content="<%= website_title %>"/>
  <meta property="og:url" content="http://connect-chennai.codeastra.com/"/>
  <meta property="og:type" content="website"/>
  <meta property="og:description" content="<%= website_description %>"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "common/header" %>
  <div class="container">
    <div class="flash_messages">
      <%= flash_tag(notice, "notice") %>
      <%= flash_tag(alert, "alert") %>
    </div>
    <%= yield %>
  </div>
  <%= render "common/footer" %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-71090418-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>

app/views/needees/index.html.erb
<form class="well form-inline" action="<%= needees_path %>" method="get">
  <div class="form-group">
    <label>I would like to help in: </label>
    <%= select_tag(:help_type, options_for_select(Needee::HelpType.helps, @help_type), class: "form-control") %>
  </div>
  <div class="form-group">
    <label> at: </label>
    <%= select_tag(:locality_id, options_for_select(@localities.collect{|loc| [loc.name, loc.id]}, @locality_id), class: "form-control") %>
  </div>
  <button type="submit" class="btn btn-primary">Go!</button>
</form>

<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#needees" aria-controls="home" role="tab" data-toggle="tab">People in Need</a></li>
  <li role="presentation"><a href="#volunteers" aria-controls="profile" role="tab" data-toggle="tab">Volunteers Who can Help You</a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="needees">

    <% if @needees.any? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Locality</th>
            <th>Help Needed</th>
            <th>Phone</th>
            <th>Alt. Phone</th>
            <th>Address</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          <% (0...@needees.count).each do |i| %>
            <% needee = @needees[i] %>
            <tr>
              <td><%= needee.id %></td>
              <td><%= needee.name %></td>
              <td><%= @localities.select{|loc| loc.id == needee.locality_id}.first.name %></td>
              <td><%= Needee::HelpType.help_name(needee.type_of_help) %></td>
              <td><%= needee.phone %></td>
              <td><%= needee.alt_phone %></td>
              <td><%= raw needee.address.gsub("\n", "<br>") %></td>
              <td><%= raw needee.details.gsub("\n", "<br>") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="well">
        <h4>
          There are no people looking for need in this locality at this point of time.<br>
          Please try another nearby locality.
        </h4>
      </div>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="volunteers">
    <% if @volunteers.any? %>
      <div class="well">
        <h4>
          You may consider working with the following volunteers.
        </h4>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
          </tr>
        </thead>
        <tbody>
          <% @volunteers.each do |vol| %>
            <tr>
              <td><%= vol.name %></td>
              <td><%= vol.phone %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="well">
        <h4>
          There are no volunteers in this locality at this point of time.
        </h4>
      </div>
    <% end %>
  </div>
</div>

app/views/needees/new.html.erb
<%= simple_form_for @needee do |f| %>
  <%= f.input :name %>
  <%= f.input :phone %>
  <%= f.input :alt_phone, label: "Alternate Phone Number", hint: "If you are posting for someone, please provide your phone number" %>
  <%= f.input :locality_id, collection: @localities, label_method: :name, value_method: :id, include_blank: false %>
  <%= f.input :type_of_help, collection: Needee::HelpType.needs, label_method: :text, value_method: :code, include_blank: false %>
  <%= f.input :address %>
  <%= f.input :details, placeholder: "Please provide any information that will help us find you" %>
  <%= recaptcha_tags %>
  <%= f.submit "Help Me", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/users/edit.html.erb
<h3>Please tell us a bit about you, so that we can better map you to the appropriate needy.</h3>
<%= simple_form_for current_user do |f| %>
  <%= f.input :locality_id, label: "Which area would you like to work in?", collection: @localities, label_method: :name, value_method: :id, include_blank: false %>
  <%= f.input :type_of_help, label: "What kind of help would you like to offer?", collection: Needee::HelpType.all_needs, label_method: :text, value_method: :code, include_blank: false  %>
  <%= f.input :phone, label: "Phone number on which we can reach you" %>
  <%= f.submit "Save my preferences", class: "btn btn-primary" %>
<% end %>